"""
Parity harness — does scripts/train.py reproduce the historical training loop?

results/metrics.csv holds the original single-seed (42) A/D/B runs produced by
notebooks/04_train.ipynb before the loop was factored into scripts/train.py.
This re-runs those 15 combinations through train.py and reports the largest
deviation, so the refactor can be shown not to have changed the numbers.

Training is bit-deterministic on a fixed machine but NOT across platforms, so
the residual depends on where metrics.csv was generated. The report records the
platform alongside the deviation.

Run:  python3 scripts/verify_parity.py     ->  results/parity_report.md
"""

from __future__ import annotations

import platform
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
from train import SPLIT_NAMES, train_one  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results"
MODELS = ("A", "D", "B")
SEED = 42


def main():
    ref = pd.read_csv(RES / "metrics.csv")
    ref = ref.drop_duplicates(["model", "split", "seed"], keep="last")
    ref = ref.set_index(["model", "split", "seed"])

    rows = []
    for kind in MODELS:
        for split in SPLIT_NAMES:
            key = (kind, split, SEED)
            if key not in ref.index:
                print(f"[skip] {kind}/{split}: not in metrics.csv")
                continue
            metrics, elapsed, _ = train_one(kind, split, SEED, verbose=False)
            for phase in ("train", "val", "test"):
                rows.append({
                    "model": kind, "split": split, "phase": phase,
                    "reference": float(ref.loc[key, f"{phase}_rmse"]),
                    "reproduced": metrics[phase]["rmse"],
                })
            print(f"{kind}/{split:<9} test  ref={ref.loc[key,'test_rmse']:.6f}  "
                  f"new={metrics['test']['rmse']:.6f}  "
                  f"|d|={abs(ref.loc[key,'test_rmse']-metrics['test']['rmse']):.2e}  "
                  f"({elapsed:.0f}s)", flush=True)

    df = pd.DataFrame(rows)
    df["abs_diff"] = (df.reproduced - df.reference).abs()
    worst = df.loc[df.abs_diff.idxmax()]

    # Same-machine reference, when one exists. metrics.csv was generated on
    # different hardware, so a deviation against it conflates two things: the
    # refactor, and platform float differences. metrics_stage4.csv holds the
    # same 15 combinations produced on THIS machine by the pre-refactor
    # loop, which isolates the refactor alone. Regenerated by notebook 06.
    same_machine = None
    sm_path = RES / "metrics_stage4.csv"
    if sm_path.exists():
        sm = pd.read_csv(sm_path)
        sm = sm[sm.seed == SEED].set_index(["model", "split"])["test_rmse"]
        test = df[df.phase == "test"].set_index(["model", "split"])["reproduced"]
        common = [k for k in test.index if k in sm.index]
        if common:
            same_machine = pd.Series(
                {k: abs(test[k] - sm[k]) for k in common}, name="abs_diff")

    lines = [
        "# Parity report — scripts/train.py vs the historical notebook loop\n",
        f"Platform: {platform.platform()}, python {platform.python_version()}, "
        f"torch {torch.__version__}, {torch.get_num_threads()} threads.\n",
    ]

    if same_machine is not None:
        lines += [
            "## Refactor parity (same machine)\n",
            "Against `results/metrics_stage4.csv` — the same 15 combinations run on "
            "this machine by the pre-refactor loop. This is the comparison that "
            "isolates the refactor.\n",
            f"- combinations: **{len(same_machine)}**",
            f"- **max |delta test RMSE| = {same_machine.max():.3e}**",
            "",
            ("**Bit-exact.** `train.py` reproduces the pre-refactor loop with zero "
             "deviation.\n" if same_machine.max() == 0 else
             f"Largest deviation at {same_machine.idxmax()}.\n"),
        ]

    lines += [
        "## Cross-platform comparison\n",
        f"Against `results/metrics.csv`, the original seed-{SEED} A/D/B runs, which "
        "were produced on different hardware (its audit log records a Linux path).\n",
        f"- comparisons: **{len(df)}** (train/val/test RMSE for "
        f"{df.groupby(['model','split']).ngroups} combinations)",
        f"- **max |delta RMSE| = {df.abs_diff.max():.3e}**  "
        f"({worst.model}/{worst.split}, {worst.phase})",
        f"- median |delta RMSE| = {df.abs_diff.median():.3e}\n",
        "| model | split | max \\|delta\\| over phases |",
        "|---|---|---:|",
    ]
    for (m, s_) in sorted(df.groupby(["model", "split"]).groups):
        g = df[(df.model == m) & (df.split == s_)]
        lines.append(f"| {m} | {s_} | {g.abs_diff.max():.2e} |")

    lines += [
        "",
        "These deviations are far larger than raw float noise (~1e-4, seen at "
        "B/coldsolv) because early stopping is a **discrete** choice: a tiny "
        "difference in float reduction order changes which epoch wins on "
        "validation, and therefore which checkpoint is kept. All three models "
        "are affected, and the magnitudes are largest on the cold splits, where "
        "validation curves are flattest and epoch selection is close to tied.",
        "",
        "Cross-platform numbers are therefore not a refactor check. Reproduce on "
        "one machine and compare within it.",
    ]

    (RES / "parity_report.md").write_text("\n".join(lines) + "\n")
    df.to_csv(RES / "parity_detail.csv", index=False)
    print(f"\nmax |delta RMSE| vs metrics.csv      = {df.abs_diff.max():.3e}")
    if same_machine is not None:
        print(f"max |delta RMSE| vs same-machine ref  = {same_machine.max():.3e}")
    print("-> results/parity_report.md")


if __name__ == "__main__":
    main()
